[book]
author = "Gabriel Sanches"
language = "en"
multilingual = false
src = "src"
title = "Gabriel Sanches's Handbook"

[output.html]
additional-css = [
  "theme/light.css",
  "theme/dark.css",
]
copy-fonts = false
default-theme = "dark"
preferred-dark-theme = "dark"

[output.html.playground]
copyable = false
