[book]
author = "Gabriel Sanches"
language = "en"
multilingual = false
src = "src"
title = "Gabriel Sanches's Handbook"

[output.html]
additional-css = [
  "theme/light.css",
  "theme/dark.css",
]
default-theme = "dark"
preferred-dark-theme = "dark"
git-repository-url = "https://github.com/gbrlsnchs/handbook"

[output.html.playground]
copyable = false
